// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkvsGdsoPM04_1ODCcdwlAzXRXtGBRfEc',
    appId: '1:91184701354:web:2b31543b06b96da03e95d3',
    messagingSenderId: '91184701354',
    projectId: 'aidea-90e12',
    authDomain: 'aidea-90e12.firebaseapp.com',
    storageBucket: 'aidea-90e12.firebasestorage.app',
    measurementId: 'G-F3WBVJ1FZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlZGNlf5yGCKB7UmbM8yX5VpZTEswjrM',
    appId: '1:91184701354:android:8f968608ceeb40c03e95d3',
    messagingSenderId: '91184701354',
    projectId: 'aidea-90e12',
    storageBucket: 'aidea-90e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTIeXSotoZJlqo_jsOWiCCDtfhFnVjdrc',
    appId: '1:91184701354:ios:b0e4756f3171e68e3e95d3',
    messagingSenderId: '91184701354',
    projectId: 'aidea-90e12',
    storageBucket: 'aidea-90e12.firebasestorage.app',
    iosBundleId: 'com.aideaApp.aidea',
  );
}
